[project]
name = "ai-grand-prix"
version = "0.1.0"
description = "MAVLink client for Anduril's AI Grand Prix simulator"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium",
    "keyboard",
    "matplotlib",
    "numpy",
    "opencv-python",
    "pymavlink",
    "python-dotenv",
    "rich",
    "stable-baselines3",
    "tensorboard",
]

[tool.uv]
package = false
